### ISSUE TITLE
Not letting me mark as complete

### ISSUE THREAD

**Issue by A-Glazer** [learn-co-curriculum/yield-and-return-values#10]
This lab isn't letting me mark as complete since there are no specs. "Submit pull requests" isn't highlighting and it won't let me do "learn submit"

**Comment by drakeltheryuujin** [comment]
Hi @A-Glazer,

This request sounds like an improvement to or a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.), versus bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
