### ISSUE TITLE
My Spec file is missing

### ISSUE THREAD

**Issue by kiranram90** [learn-co-curriculum/yield-and-return-values#14]
I keep deleting the repository but it is not resetting my file for me to complete this lab

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
