### ISSUE TITLE
Return from Yield Statement

### ISSUE THREAD

**Issue by jimmyle414** [learn-co-curriculum/yield-and-return-values#16]
Hi! I need help running this test and submit the test.

This is the error message I got.

[07:06:00] (master) yield-and-return-values-online-web-sp-000
// ♥ learn
This directory doesn't appear to have any specs in it.
[07:09:35] (master) yield-and-return-values-online-web-sp-000
// ♥

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
