### ISSUE TITLE
The lesson needs to specify certain things

### ISSUE THREAD

**Issue by CodeByLine** [learn-co-curriculum/yield-and-return-values#4]
If rspec expects specific terms to be used, such "my_collect" or "languages", the lesson should state it as such. Otherwise, a student ends up spending a lot of time tweaking code, only to discover it's the array name that needed to be changed.

**Comment by AnnJohn** [comment]
Hi @CodeByLine this issue might be related to a different lesson so I'm going to close it here, as there are no spec files in this lab. Thanks.

**Comment by CodeByLine** [comment]
OK
